from app.models import db, Project_media


# Adds a demo project_media, you can add other project_medias here if you want
def seed_project_medias():

    project_media_1 = Project_media(project_id=1, media_url="https://th.bing.com/th/id/OIP._jt9zAneTFLbYSCVoKW16AHaE8?pid=ImgDet&rs=1")
    project_media_2 = Project_media(project_id=1, media_url="https://media.istockphoto.com/photos/sick-child-asleep-in-hospital-bed-with-gown-and-canula-picture-id467796216")
    project_media_3 = Project_media(project_id=1, media_url="https://thumbs.dreamstime.com/b/children-patient-hospital-bed-closing-his-face-38625529.jpg")
    project_media_4 = Project_media(project_id=1, media_url="https://i.pinimg.com/originals/0f/c4/55/0fc455dca5836a5876f759b72f422270.jpg")
    project_media_5 = Project_media(project_id=2, media_url="https://obj.ca/sites/default/files/2017-10/Make%20a%20wish%20ad.png")
    project_media_6 = Project_media(project_id=2, media_url="https://i0.wp.com/kemccann.files.wordpress.com/2009/09/make_a_wish_foundation2.jpg")
    project_media_7 = Project_media(project_id=2, media_url="https://walkwest.com/wp-content/uploads/2017/09/make-a-wish-cover.jpg")
    project_media_8 = Project_media(project_id=2, media_url="https://imagez.tmz.com/image/05/o/2013/11/18/059eb27c121550f8bc7b8ae13e23ad55_md.jpg")
    project_media_9 = Project_media(project_id=3, media_url="https://www.meltingpot.com/peninsula-va/files/3313/St-Jude-Charity-GNO-Flex-Slider.jpg")
    project_media_10 = Project_media(project_id=3, media_url="https://www.stjude.org/about-st-jude/_jcr_content/image.img.800.high.jpg/1481661651921.jpg")
    project_media_11 = Project_media(project_id=3, media_url="https://www.christopherandbanks.com/on/demandware.static/-/Sites-CBKB2C-Library/default/dw35e36bf1/images/Special_Projects/St-Jude/2016/11/st_jude_kids.jpg")
    project_media_12 = Project_media(project_id=3, media_url="https://th.bing.com/th/id/OIP.4Boozw6-QiTsj5mKIoi5iwHaHa?pid=ImgDet&rs=1")
    project_media_13 = Project_media(project_id=4, media_url="https://www.givingthroughjewelry.com/wp-content/uploads/2012/01/breastcancer.jpg")
    project_media_14 = Project_media(project_id=4, media_url="https://th.bing.com/th/id/OIP.E6c6_BmBHzztNk5CkFMC1AHaB9?pid=ImgDet&rs=1")
    project_media_15 = Project_media(project_id=4, media_url="https://www.bcrf.org/sites/default/files/styles/blog_promoted/public/blog/image/AmazonBlogHeader8.png?itok=7UZepJC6")
    project_media_16 = Project_media(project_id=4, media_url="https://www.bcrf.org/sites/default/files/blog/image/2015-10-01.jpg")
    project_media_17 = Project_media(project_id=5, media_url="https://thehillnews.org/wp-content/uploads/2015/11/159748LOGO.jpg")
    project_media_18 = Project_media(project_id=5, media_url="https://media.glassdoor.com/l/5e/aa/23/39/corporate-center.jpg")
    project_media_19 = Project_media(project_id=5, media_url="https://goshennychamber.com/wp-content/uploads/2020/02/American-Cancer-Society-Making-Strides-Logo-scaled.jpg")
    project_media_20 = Project_media(project_id=5, media_url="https://www.activacuity.com/wp-content/uploads/2017/01/ACS-Mission-Statement-Pinup.jpg")
    project_media_21 = Project_media(project_id=6, media_url="https://tuitionchart.com/images/scholarship-america.jpg")
    project_media_22 = Project_media(project_id=6, media_url="https://pq-resources.s3.amazonaws.com/partner_logos/400x225/Scholarship-America.jpg")
    project_media_23 = Project_media(project_id=6, media_url="https://scholarshipamerica.org/wp-content/uploads/2019/04/d2s-email-details.png")
    project_media_24 = Project_media(project_id=6, media_url="https://online.champlain.edu/sites/online/files/2020-02/scholarsip%20america%201900x450.jpg")
    project_media_25 = Project_media(project_id=7, media_url="http://ww1.prweb.com/prfiles/2018/11/20/15938747/ProLiteracy+Logo+1.png")
    project_media_26 = Project_media(project_id=7, media_url="https://proliteracy.org/portals/0/Images/Banners/Hero/2018-09-ProLiteracyHeroContest-HomepageBanner-v02.png?ver=2018-09-12-120248-707%C3%97tamp=1536768176818")
    project_media_27 = Project_media(project_id=7, media_url="http://ww1.prweb.com/prfiles/2015/08/26/12927402/ProLiteracy-DoG-logo-tagline.jpg")
    project_media_28 = Project_media(project_id=7, media_url="https://edtech.worlded.org/wp-content/uploads/2020/09/ProLiteracy-World-Ed-banner-1024x426.png")
    project_media_29 = Project_media(project_id=8, media_url="https://www.womenshelters.org/gallery/4181_quigley-house-inc_dbv.fna&oh=c0dba0e6d23587ac702f73a4285ae77a&oe=5C7B8D7E")
    project_media_30 = Project_media(project_id=8, media_url="https://s3.amazonaws.com/gs-waymarking-images/cef3d59b-92ce-432b-8ff8-9d24ac915205_d.jpeg")
    project_media_31 = Project_media(project_id=8, media_url="https://cdn4.creativecirclemedia.com/claytoday/original/20200128-151232-Quigley%20House%20DD%20Susan%20Atwell%20013020.jpg")
    project_media_32 = Project_media(project_id=8, media_url="https://cdn4.creativecirclemedia.com/claytoday/original/20201013-111034-Quigley%20House%20domestic%20violence%20101520.jpg")
    project_media_33 = Project_media(project_id=9, media_url="https://www.looktothestars.org/photo/9046-prevent-child-abuse-america/story_half_width.jpg")
    project_media_34 = Project_media(project_id=9, media_url="https://www.clipartkey.com/mpngs/m/200-2000513_prevent-child-abuse-america.png")
    project_media_35 = Project_media(project_id=9, media_url="https://logos-download.com/wp-content/uploads/2019/06/Prevent_Child_Abuse_America_Logo_full.png")
    project_media_36 = Project_media(project_id=9, media_url="https://www.nolove4.com/assets/images/products/136932960_preview_637080678808816581.png")
    project_media_37 = Project_media(project_id=10, media_url="https://www.thefix.com/sites/default/files/naturalhigh.jpg")
    project_media_38 = Project_media(project_id=10, media_url="https://www.naturalhigh.org/wp-content/uploads/2020/05/CTA-for-Blog-Images-5-1024x536.png")
    project_media_39 = Project_media(project_id=10, media_url="https://yt3.ggpht.com/a/AATXAJz8APJgVQujX8hKl8L7v5nxSmSocJLpBNXDbA=s900-c-k-c0xffffffff-no-rj-mo")
    project_media_40 = Project_media(project_id=10, media_url="https://th.bing.com/th/id/OIP.iuERVCEbE8Vdl6e_nQPlPgHaFu?pid=ImgDet&rs=1")
    project_media_41 = Project_media(project_id=11, media_url="https://yt3.ggpht.com/a/AGF-l788Rg8xD24TdcJB-sVb4-rps8FTKqnJUxsvRQ=s900-c-k-c0xffffffff-no-rj-mo")
    project_media_42 = Project_media(project_id=11, media_url="https://www.awareness-foundation.com/wp-content/uploads/2020/04/Ambassadors-for-peace-logo.png")
    project_media_43 = Project_media(project_id=11, media_url="https://www.awareness-foundation.com/wp-content/uploads/2020/04/little-heroes-logo.png")
    project_media_44 = Project_media(project_id=11, media_url="https://www.awareness-foundation.com/wp-content/uploads/2020/04/donate-icon-2.png")
    project_media_45 = Project_media(project_id=12, media_url="https://getlogovector.com/wp-content/uploads/2019/05/world-central-kitchen-logo-vector.png")
    project_media_46 = Project_media(project_id=12, media_url="https://i.ytimg.com/vi/XZ2kdZafGws/maxresdefault.jpg")
    project_media_47 = Project_media(project_id=12, media_url="https://ewscripps.brightspotcdn.com/dims4/default/b58c9fe/2147483647/strip/true/crop/5205x2928+0+271/resize/1280x720!/quality/90/?url=http:%2F%2Fewscripps-brightspot.s3.amazonaws.com%2Fe6%2Fbf%2Fcf0995f64e618a30d1c9cf4f45d8%2Fap-20199676213013.jpg")
    project_media_48 = Project_media(project_id=12, media_url="https://www.periodismogastronomico.com/wp-content/uploads/2020/05/Captura-de-pantalla-2020-05-19-a-las-12.11.15.png")
    project_media_49 = Project_media(project_id=13, media_url="https://www.researchforgood.com/wp-content/uploads/2012/01/Eng_Col_RGB_Large.png")
    project_media_50 = Project_media(project_id=13, media_url="https://foodieeshe.com/wp-content/uploads/2017/03/Action-Against-Hunger.jpg")
    project_media_51 = Project_media(project_id=13, media_url="https://cfanj.org/wp-content/uploads/2019/09/sctio-1100x564.png")
    project_media_52 = Project_media(project_id=13, media_url="http://kathmandu.im/wp-content/uploads/2012/02/Action-Against-Hunger.jpg")
    project_media_53 = Project_media(project_id=14, media_url="https://cdn.jewishboston.com/uploads/2021/06/Amit-Paley-headshot-729x486.jpg")
    project_media_54 = Project_media(project_id=14, media_url="https://gray-wbko-prod.cdn.arcpublishing.com/resizer/ib2fribTAJN7WWaH7kxEHSRXXtI=/1200x675/smart/cloudfront-us-east-1.images.arcpublishing.com/gray/QCMFZHQVKFG2DKETESRTNLUMAE.jpg")
    project_media_55 = Project_media(project_id=14, media_url="https://vivaredlight.com/wp-content/uploads/2021/06/NFL-To-Match-Carl-Nassibs-100000-Donation-To-The-Trevor-768x448.jpg")
    project_media_56 = Project_media(project_id=14, media_url="https://public.newsdirect.com/750702674/fI0TeQ8A.png")
    project_media_57 = Project_media(project_id=15, media_url="https://mma.prnewswire.com/media/491910/American_Foundation_for_Suicide_Prevention_Logo.jpg?p=facebook")
    project_media_58 = Project_media(project_id=15, media_url="https://gray-wdtv-prod.cdn.arcpublishing.com/resizer/EhOKjYIQ-VzZD4lj8rUqHDFQz7Y=/1200x675/smart/cloudfront-us-east-1.images.arcpublishing.com/gray/W3RUIQMWJBNWPGSPUNKMTIBUKQ.jpg")
    project_media_59 = Project_media(project_id=15, media_url="https://suicideprevention.osu.edu/files/2015/06/Community-Walk-Logo.jpeg")
    project_media_60 = Project_media(project_id=15, media_url="https://www.datocms-assets.com/12810/1564317254-13912afspproject2025graphics1080x1080m1.png?w=1000&fit=max&fm=jpg")
    project_media_61 = Project_media(project_id=16, media_url="http://ww1.prweb.com/prfiles/2009/12/10/1098764/Homelesslogo.jpg")
    project_media_62 = Project_media(project_id=16, media_url="https://endhomelessness.org/wp-content/uploads/2016/10/2016update.png")
    project_media_63 = Project_media(project_id=16, media_url="https://www.charitychoices.com/sites/default/files/NatlAllianceEndHomeless_AWE2013.jpg")
    project_media_64 = Project_media(project_id=16, media_url="https://homelesshub.ca/sites/default/files/Instagram-Post.png")
    project_media_65 = Project_media(project_id=17, media_url="http://cdn.greatnonprofits.org/images/logos/CHPLOGO1.jpg")
    project_media_66 = Project_media(project_id=17, media_url="https://www.indybay.org/uploads/2014/11/05/800_symposium_poster_-_header.jpg?4321")
    project_media_67 = Project_media(project_id=17, media_url="https://www.shelterlist.com/gallery/_mgtaqvtx.png")
    project_media_68 = Project_media(project_id=17, media_url="https://media.glassdoor.com/banner/bh/434305/community-housing-partnership-banner-1467398174599.jpg")
    project_media_69 = Project_media(project_id=18, media_url="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/MDA.svg/1200px-MDA.svg.png")
    project_media_70 = Project_media(project_id=18, media_url="https://i.pinimg.com/originals/ab/1d/72/ab1d72d2b89e8c4bc9fc7e7c7e01ccab.jpg")
    project_media_71 = Project_media(project_id=18, media_url="https://media.glassdoor.com/banner/bh/17718/muscular-dystrophy-association-banner-1469127543153.jpg")
    project_media_72 = Project_media(project_id=18, media_url="https://ionnews.mu/wp-content/uploads/2015/09/Muscular-Dystrophy-Association-pic.jpg")
    project_media_73 = Project_media(project_id=19, media_url="https://th.bing.com/th/id/OIP.jRV4zvKNK1uz7nKhd5byagHaEi?pid=ImgDet&rs=1")
    project_media_74 = Project_media(project_id=19, media_url="https://indyhub.org/wp-content/uploads/7-17.png")
    project_media_75 = Project_media(project_id=19, media_url="https://esperare.org/sites/default/files/content/Documents/graphic_dmd.png")
    project_media_76 = Project_media(project_id=19, media_url="https://www.tbhcreative.com/userfiles/image/portfolio/projects/1775/mdff-home-mobile.png")
    project_media_77 = Project_media(project_id=20, media_url="https://usdailyreview.com/wp-content/uploads/2013/08/AMERICAN-HUMANE-.jpg")
    project_media_78 = Project_media(project_id=20, media_url="https://city-sentinel.com/wp-content/uploads/2016/05/AHA-logo.jpg")
    project_media_79 = Project_media(project_id=20, media_url="https://cdn.greatnonprofits.org/images/uploads/organizations/fbalbum_101544537792924540.jpg")
    project_media_80 = Project_media(project_id=20, media_url="https://vignette.wikia.nocookie.net/logo-timeline/images/9/99/6BB9C3BB-653D-4C67-8606-CC758C649181.png/revision/latest?cb=20200531031059")
    project_media_81 = Project_media(project_id=21, media_url="https://blog.pch.com/wp-content/uploads/2013/11/aspca-group-1024x592.jpg")
    project_media_82 = Project_media(project_id=21, media_url="https://yt3.ggpht.com/a/AGF-l78t9R8HGaUBFAc5uSx8E_7C33mdm6Y-M4kZcg=s900-c-k-c0xffffffff-no-rj-mo")
    project_media_83 = Project_media(project_id=21, media_url="https://www.webwiki.com/etc/sslimage.php?security=cb3a5416902479f1b35fa657543877df&url=http:%2F%2Fwww.aspca.org%2Fsites%2Fdefault%2Ffiles%2Faspca.jpg")
    project_media_84 = Project_media(project_id=21, media_url="https://secure.aspca.org/files/aspca/social_images/join-aspca-advo-brigade_080416_fb.jpg")
    project_media_85 = Project_media(project_id=22, media_url="https://charity-tree.s3.amazonaws.com/c2061fee9e12437087a6caf26ac1bd07.png")
    project_media_86 = Project_media(project_id=22, media_url="https://charity-tree.s3.amazonaws.com/ceb075d2fc2940e3b9e87ce4859f3d5b.png")
    project_media_87 = Project_media(project_id=22, media_url="https://charity-tree.s3.amazonaws.com/eadcde8d8a8e4782aaaaa96c489d7b1c.png")
    project_media_88 = Project_media(project_id=22, media_url="https://charity-tree.s3.amazonaws.com/dcebbf61c34945d484429fd2ef9b590c.png")

    db.session.add(project_media_1)
    db.session.add(project_media_2)
    db.session.add(project_media_3)
    db.session.add(project_media_4)
    db.session.add(project_media_5)
    db.session.add(project_media_6)
    db.session.add(project_media_7)
    db.session.add(project_media_8)
    db.session.add(project_media_9)
    db.session.add(project_media_10)
    db.session.add(project_media_11)
    db.session.add(project_media_12)
    db.session.add(project_media_13)
    db.session.add(project_media_14)
    db.session.add(project_media_15)
    db.session.add(project_media_16)
    db.session.add(project_media_17)
    db.session.add(project_media_18)
    db.session.add(project_media_19)
    db.session.add(project_media_20)
    db.session.add(project_media_21)
    db.session.add(project_media_22)
    db.session.add(project_media_23)
    db.session.add(project_media_24)
    db.session.add(project_media_25)
    db.session.add(project_media_26)
    db.session.add(project_media_27)
    db.session.add(project_media_28)
    db.session.add(project_media_29)
    db.session.add(project_media_30)
    db.session.add(project_media_31)
    db.session.add(project_media_32)
    db.session.add(project_media_33)
    db.session.add(project_media_34)
    db.session.add(project_media_35)
    db.session.add(project_media_36)
    db.session.add(project_media_37)
    db.session.add(project_media_38)
    db.session.add(project_media_39)
    db.session.add(project_media_40)
    db.session.add(project_media_41)
    db.session.add(project_media_42)
    db.session.add(project_media_43)
    db.session.add(project_media_44)
    db.session.add(project_media_45)
    db.session.add(project_media_46)
    db.session.add(project_media_47)
    db.session.add(project_media_48)
    db.session.add(project_media_49)
    db.session.add(project_media_50)
    db.session.add(project_media_51)
    db.session.add(project_media_52)
    db.session.add(project_media_53)
    db.session.add(project_media_54)
    db.session.add(project_media_55)
    db.session.add(project_media_56)
    db.session.add(project_media_57)
    db.session.add(project_media_58)
    db.session.add(project_media_59)
    db.session.add(project_media_60)
    db.session.add(project_media_61)
    db.session.add(project_media_62)
    db.session.add(project_media_63)
    db.session.add(project_media_64)
    db.session.add(project_media_65)
    db.session.add(project_media_66)
    db.session.add(project_media_67)
    db.session.add(project_media_68)
    db.session.add(project_media_69)
    db.session.add(project_media_70)
    db.session.add(project_media_71)
    db.session.add(project_media_72)
    db.session.add(project_media_73)
    db.session.add(project_media_74)
    db.session.add(project_media_75)
    db.session.add(project_media_76)
    db.session.add(project_media_77)
    db.session.add(project_media_78)
    db.session.add(project_media_79)
    db.session.add(project_media_80)
    db.session.add(project_media_81)
    db.session.add(project_media_82)
    db.session.add(project_media_83)
    db.session.add(project_media_84)
    # db.session.add(project_media_85)
    # db.session.add(project_media_86)
    # db.session.add(project_media_87)
    # db.session.add(project_media_88)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the project_medias table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key
def undo_project_medias():
    db.session.execute('TRUNCATE project_medias RESTART IDENTITY CASCADE;')
    db.session.commit()
