from app.models import db, Tier


# Adds a demo tier, you can add other tiers here if you want
def seed_tiers():

    demo_tier_1 = Tier(name='Silver', value=100, description="Donate $100 and get a free t-shirt saying I saved a life today.", project_id=1)
    demo_tier_2 = Tier(name='Gold', value=250, description="Donate $250 and get a personalized thank you card from the child that you helped with their medical bills.", project_id=1)
    demo_tier_3 = Tier(name='Platinum', value=500, description="Donate $500 and get to come visit the child that you helped save for a day, complete with videogames and/or movies, plus a dinner of your choice.", project_id=1)
    demo_tier_4 = Tier(name='Silver', value=100, description="Donate $100 and get a free Make A Wish keychain, plus a thank you letter from each child your donation helped save.", project_id=2)
    demo_tier_5 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=2)
    demo_tier_6 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the child that your donation helped.", project_id=2)
    demo_tier_7 = Tier(name='Silver', value=100, description="Donate $100 and get a free St. Jude keychain, plus a thank you letter from each child your donation helped save.", project_id=3)
    demo_tier_8 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=3)
    demo_tier_9 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the child that your donation helped.", project_id=3)
    demo_tier_10 = Tier(name='Silver', value=100, description="Donate $100 and get a free Breast Cancer Research Foundation keychain, plus a thank you letter from each person your donation helped save.", project_id=4)
    demo_tier_11 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=4)
    demo_tier_12 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with a person that your donation helped.", project_id=4)
    demo_tier_13 = Tier(name='Silver', value=100, description="Donate $100 and get a free American Cancer Society keychain, plus a thank you letter from each person your donation helped save.", project_id=5)
    demo_tier_14 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=5)
    demo_tier_15 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped.", project_id=5)
    demo_tier_16 = Tier(name='Silver', value=100, description="Donate $100 and get a free Scholarship America keychain, plus a thank you letter from each person whose education your donation helped fund.", project_id=6)
    demo_tier_17 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=6)
    demo_tier_18 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped.", project_id=6)
    demo_tier_19 = Tier(name='Silver', value=100, description="Donate $100 and get a free ProLiteracy keychain, plus a thank you letter from each person whose education your donation helped fund.", project_id=7)
    demo_tier_20 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=7)
    demo_tier_21 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped.", project_id=7)
    demo_tier_22 = Tier(name='Silver', value=100, description="Donate $100 and get a free Quigley House keychain, plus a thank you letter from each person your donation helped save.", project_id=8)
    demo_tier_23 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=8)
    demo_tier_24 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped.", project_id=8)
    demo_tier_25 = Tier(name='Silver', value=100, description="Donate $100 and get a free Prevent Child Abuse keychain, plus a thank you letter from each child your donation helped save.", project_id=9)
    demo_tier_26 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=9)
    demo_tier_27 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped.", project_id=9)
    demo_tier_28 = Tier(name='Silver', value=100, description="Donate $100 and get a free Natural High keychain, plus a thank you letter from each person your donation helped save.", project_id=10)
    demo_tier_29 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=10)
    demo_tier_30 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped.", project_id=10)
    demo_tier_31 = Tier(name='Silver', value=100, description="Donate $100 and get a free Awareness Foundation keychain, plus a thank you letter from each charity your donation helped spread awareness for.", project_id=11)
    demo_tier_32 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=11)
    demo_tier_33 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with touring one of the charities that your donation helped raise awareness for.", project_id=11)
    demo_tier_34 = Tier(name='Silver', value=100, description="Donate $100 and get a free World Central Kitchen keychain, plus a thank you letter from each person your donation helped feed.", project_id=12)
    demo_tier_35 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=12)
    demo_tier_36 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with a person that your donation fed.", project_id=12)
    demo_tier_37 = Tier(name='Silver', value=100, description="Donate $100 and get a free Action Agaainst Hunger keychain, plus a thank you letter from each person your donation helped feed.", project_id=13)
    demo_tier_38 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=13)
    demo_tier_39 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with a person that your donation fed.", project_id=13)
    demo_tier_40 = Tier(name='Silver', value=100, description="Donate $100 and get a free The Trevor Project keychain, plus a thank you letter from each person your donation helped save.", project_id=14)
    demo_tier_41 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=14)
    demo_tier_42 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped.", project_id=14)
    demo_tier_43 = Tier(name='Silver', value=100, description="Donate $100 and get a free American Foundation for Suicide Prevention keychain, plus a thank you letter from each person your donation helped save.", project_id=15)
    demo_tier_44 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=15)
    demo_tier_45 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped.", project_id=15)
    demo_tier_46 = Tier(name='Silver', value=100, description="Donate $100 and get a free The National Alliance to End Homelessness keychain, plus a thank you letter from each person your donation helped house.", project_id=16)
    demo_tier_47 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=16)
    demo_tier_48 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped house.", project_id=16)
    demo_tier_49 = Tier(name='Silver', value=100, description="Donate $100 and get a free Community Housing Partnership keychain, plus a thank you letter from each person your donation helped house.", project_id=17)
    demo_tier_50 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=17)
    demo_tier_51 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped house.", project_id=17)
    demo_tier_52 = Tier(name='Silver', value=100, description="Donate $100 and get a free Muscular Dystrophy Association keychain, plus a thank you letter from each person your donation helped save.", project_id=18)
    demo_tier_53 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=18)
    demo_tier_54 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped.", project_id=18)
    demo_tier_55 = Tier(name='Silver', value=100, description="Donate $100 and get a free Muscular Dystrophy Family Foundation keychain, plus a thank you letter from each family your donation helped save.", project_id=19)
    demo_tier_56 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=19)
    demo_tier_57 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with the person that your donation helped.", project_id=19)
    demo_tier_58 = Tier(name='Silver', value=100, description="Donate $100 and get a free American Humane keychain, plus a letter of thanks and a photo of each animal your donation helped save.", project_id=20)
    demo_tier_59 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=20)
    demo_tier_60 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with an animal that your donation helped save.", project_id=20)
    demo_tier_61 = Tier(name='Silver', value=100, description="Donate $100 and get a free The American Society for the Prevention of Cruelty to Animals keychain, plus a letter of thanks and a photo of each animal your donation helped save", project_id=21)
    demo_tier_62 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=21)
    demo_tier_63 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend a day with an animal that your donation helped save.", project_id=21)
    demo_tier_64 = Tier(name='Silver', value=100, description="Donate $100 and get a free The Little Donny Foundation keychain, plus a thank you letter from Little Donny himself.", project_id=22)
    demo_tier_65 = Tier(name='Gold', value=250, description="Donate $250 and get a free t-shirt showing your support.", project_id=22)
    demo_tier_66 = Tier(name='Platinum', value=500, description="Donate $500 and get to spend the day with Little Donny himself.", project_id=22)

    db.session.add(demo_tier_1)
    db.session.add(demo_tier_2)
    db.session.add(demo_tier_3)
    db.session.add(demo_tier_4)
    db.session.add(demo_tier_5)
    db.session.add(demo_tier_6)
    db.session.add(demo_tier_7)
    db.session.add(demo_tier_8)
    db.session.add(demo_tier_9)
    db.session.add(demo_tier_10)
    db.session.add(demo_tier_11)
    db.session.add(demo_tier_12)
    db.session.add(demo_tier_13)
    db.session.add(demo_tier_14)
    db.session.add(demo_tier_15)
    db.session.add(demo_tier_16)
    db.session.add(demo_tier_17)
    db.session.add(demo_tier_18)
    db.session.add(demo_tier_19)
    db.session.add(demo_tier_20)
    db.session.add(demo_tier_21)
    db.session.add(demo_tier_22)
    db.session.add(demo_tier_23)
    db.session.add(demo_tier_24)
    db.session.add(demo_tier_25)
    db.session.add(demo_tier_26)
    db.session.add(demo_tier_27)
    db.session.add(demo_tier_28)
    db.session.add(demo_tier_29)
    db.session.add(demo_tier_30)
    db.session.add(demo_tier_31)
    db.session.add(demo_tier_32)
    db.session.add(demo_tier_33)
    db.session.add(demo_tier_34)
    db.session.add(demo_tier_35)
    db.session.add(demo_tier_36)
    db.session.add(demo_tier_37)
    db.session.add(demo_tier_38)
    db.session.add(demo_tier_39)
    db.session.add(demo_tier_40)
    db.session.add(demo_tier_41)
    db.session.add(demo_tier_42)
    db.session.add(demo_tier_43)
    db.session.add(demo_tier_44)
    db.session.add(demo_tier_45)
    db.session.add(demo_tier_46)
    db.session.add(demo_tier_47)
    db.session.add(demo_tier_48)
    db.session.add(demo_tier_49)
    db.session.add(demo_tier_50)
    db.session.add(demo_tier_51)
    db.session.add(demo_tier_52)
    db.session.add(demo_tier_53)
    db.session.add(demo_tier_54)
    db.session.add(demo_tier_55)
    db.session.add(demo_tier_56)
    db.session.add(demo_tier_57)
    db.session.add(demo_tier_58)
    db.session.add(demo_tier_59)
    db.session.add(demo_tier_60)
    db.session.add(demo_tier_61)
    db.session.add(demo_tier_62)
    db.session.add(demo_tier_63)
    db.session.add(demo_tier_64)
    db.session.add(demo_tier_65)
    db.session.add(demo_tier_66)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the tiers table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key
def undo_tiers():
    db.session.execute('TRUNCATE tiers RESTART IDENTITY CASCADE;')
    db.session.commit()
